const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
qa('[data-scroll]').forEach(b=>b.addEventListener('click',()=>{const el=document.getElementById(b.dataset.target); if(el) el.scrollBy({left:Number(b.dataset.scroll)*Math.min(el.clientWidth*.78,460),behavior:'smooth'})}));
const menu=q('[data-menu]'),nav=q('[data-nav]'); if(menu&&nav) menu.addEventListener('click',()=>nav.classList.toggle('open'));
const modal=q('.login-modal'); qa('[data-login]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();modal?.classList.add('open')})); qa('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>modal?.classList.remove('open'))); modal?.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')}); q('#login-form')?.addEventListener('submit',e=>{e.preventDefault();modal.classList.remove('open')});

// My House demo state
const KEYS={tasks:'rinder.tasks.v3',notes:'rinder.notes.v3',activity:'rinder.activity.v3'};
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}, set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let tasks=get(KEYS.tasks,[{name:'Take out recycling',person:'Liam',done:false},{name:'Clean kitchen counters',person:'Maya',done:true}]);
let notes=get(KEYS.notes,[{text:'Could we keep the hallway clear tonight? Thanks!',time:'Earlier today'}]);
let activity=get(KEYS.activity,[{text:'Front door locked',time:'System status'}]);
function renderTasks(){const box=q('#taskList');if(!box)return;box.innerHTML=tasks.map((t,i)=>`<div class="task ${t.done?'done':''}"><button data-done="${i}" aria-label="Toggle chore">${t.done?'✓':'○'}</button><div class="task-name"><strong>${esc(t.name)}</strong><br><small>${esc(t.person)}</small></div><button data-delete="${i}" aria-label="Delete chore">×</button></div>`).join('')||'<p style="color:var(--muted)">No chores yet.</p>'; qa('[data-done]',box).forEach(b=>b.onclick=()=>{tasks[b.dataset.done].done=!tasks[b.dataset.done].done;set(KEYS.tasks,tasks);renderTasks()});qa('[data-delete]',box).forEach(b=>b.onclick=()=>{tasks.splice(b.dataset.delete,1);set(KEYS.tasks,tasks);renderTasks()})}
function renderNotes(){const box=q('#noteList');if(!box)return;box.innerHTML=notes.slice().reverse().map(n=>`<div class="note">${esc(n.text)}<time>${esc(n.time)}</time></div>`).join('')}
function renderActivity(){const box=q('#activityList');if(!box)return;box.innerHTML=activity.slice().reverse().slice(0,5).map(a=>`<div class="activity"><div style="flex:1"><strong>${esc(a.text)}</strong><br><small>${esc(a.time)}</small></div></div>`).join('')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
q('#choreForm')?.addEventListener('submit',e=>{e.preventDefault();tasks.push({name:q('#choreName').value.trim(),person:q('#chorePerson').value.trim(),done:false});set(KEYS.tasks,tasks);e.target.reset();renderTasks()});
q('#noteForm')?.addEventListener('submit',e=>{e.preventDefault();notes.push({text:q('#noteText').value.trim(),time:new Date().toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})});set(KEYS.notes,notes);e.target.reset();renderNotes()});
let doorTimer; q('#unlockDoor')?.addEventListener('click',()=>{const card=q('#doorCard'),status=q('#doorStatus'),icon=q('#doorIcon'),dot=q('#statusDot'),toast=q('#toast');card.classList.add('unlocked');status.textContent='Unlocked · auto-locking';icon.textContent='🔓';dot.style.background='#ff8f4d';activity.push({text:'Front door unlocked',time:new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})});set(KEYS.activity,activity);renderActivity();toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800);clearTimeout(doorTimer);doorTimer=setTimeout(()=>{card.classList.remove('unlocked');status.textContent='Locked · secure';icon.textContent='🔒';dot.style.background='';activity.push({text:'Front door auto-locked',time:new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})});set(KEYS.activity,activity);renderActivity()},10000)});
q('#resetDemo')?.addEventListener('click',()=>{Object.values(KEYS).forEach(k=>localStorage.removeItem(k));location.reload()});
renderTasks();renderNotes();renderActivity();
